{
  "Database":{
      "Clinics": {
          "clinicid": { 
              "location": "String",
              "center": "String",
              "addDetails":"String",
              "capacity":"number",
              "createdBy":"String",
              "date":"String",
              "clinicStatus":"String",
              "slots":"map",
              "startTime":"String",
              "timeStamp":"timeStamp",
            "Appointments":{
              "userid":{
                "called":"boolean",
                "checkedIn":"boolean",
                "calledBy":"String",
                "wasSeen":"boolean",
                "status":"String",
                "slot":"number",
                "time":"String"
              }
            }
          }
      },
      "Users":{
        "userid":{
          "ProNouns":"They/Them",
          "PhoneNumber":"String",
          "FirstName":"String",
          "MiddleName":"String",
          "LastName":"String",
          "dob":"String",
          "email":"String",
          "emailOptIn":"boolean",
          "isAgreedTC":"true",
          "Appointments":{
            "clinicid":{
              "checkedIn":"boolean",
              "calledBy":"String",
              "wasSeen":"boolean",
              "location": "String",
              "center": "String",
              "addDetails":"String",
              "clinicAddress":"String",
              "clinicPostcode":"String",
              "date":"String",
              "status":"String",
              "slot":"number",
              "startTime":"String"
            }
          },
          "Restricted":{
            "Data":{
              "role":"String",
              "accountStatus":"String"
            }
          }
        }
        
      },
      "Location":{
        "Belfast":{
          "Centers":{
            "centerid":{
              "name":"String",
              "line1":"String",
              "postcode":"String",
              "geolocation":"geopoint"
            }
          }
        }
      },
      "Mail":{
        "mailid":{
          "delivery":{
            "attempts":"number",
            "endTime":"timeStamp",
            "error":"String",
            "leaseExpireTime":"null",
            "startTime":"timeStamp",
            "state":"String"
          },
          "message":{
            "html":"String",
            "subject":"String",
            "test":"test"
          },
          "toUids":"[String]"
        }
      },
      "Questions":{
        "questionid":{
          "onAgree":"String",
          "question":"number",
          "test":"boolean"
        }
      },
      "Supporting":{
        "Data":{
          "appointmentStatus":"[{key:0, label: Active}, {key:1, label:Attended}, {key:2,label:Un-Attended},{key:3,label:Clinic Cancelled}]",
            "pronouns":"[{label:He/Him value: He/Him}, {label:She/Her, value:She/Her}, {label:They/Them, value:They/Them},{label:Prefer Not to Say, value: Prefer Not to Say}]"
        }
      }
  }
  }